"use client";

import { FaqAccordion } from "@/components/learn/FaqAccordion";

const FAQ_ITEMS = [
  {
    question: "Why does this tool sometimes recommend staying in Standard even though Glacier costs less per GB?",
    answer: "Storage price per GB is only one part of the total cost. Glacier classes charge retrieval fees every time data is accessed, and they require a minimum storage duration that triggers penalty charges if objects are deleted or moved early. For workloads with frequent access or high object churn, these additional costs can exceed the storage savings entirely. This tool models all cost components together. When Glacier is more expensive in total, the recommendation reflects that even though the storage rate alone would suggest otherwise.",
  },
  {
    question: "Why is Intelligent-Tiering sometimes more expensive than Standard?",
    answer: "Intelligent-Tiering charges a monitoring fee of $0.0025 per 1,000 objects per month for every object above 128 KB. This fee applies permanently, regardless of which tier the object is actually in. For buckets with high object counts relative to their total storage, this fee can exceed the savings generated by auto-tiering. The break-even requires roughly 255 MB of data to be tiered down to the Infrequent Access tier for every 1,000 objects being monitored.",
  },
  {
    question: "What is the difference between Monthly GET Requests and Monthly Retrieval GB?",
    answer: "Monthly GET Requests is the count of how many times objects were read, one request per read operation regardless of object size. Monthly Retrieval GB is the total volume of data actually transferred out of the bucket in those reads. A bucket with 1,000 monthly reads of 10 GB objects has 1,000 requests but 10,000 GB of retrieval. Both matter for different reasons. Request count drives request charges. Retrieval volume drives retrieval charges in IA and Glacier classes.",
  },
  {
    question: "How do I find my monthly retrieval GB?",
    answer: "Go to AWS CloudWatch, select Metrics, choose S3, and find the BytesDownloaded metric filtered to your bucket. Set the time range to the last 30 days and use the Sum statistic. The result is in bytes. Divide by 1,073,741,824 to convert to gigabytes. If CloudWatch is not available, use the estimator helper in the tool next to the Monthly Retrieval GB field.",
  },
  {
    question: "What does the confidence level change in the calculation?",
    answer: "Confidence level adjusts the tier distribution assumption used when evaluating Intelligent-Tiering. At high confidence, the model assumes a larger proportion of your data will tier down to cheaper classes. At low confidence, the model assumes most data stays in the Frequent Access tier, producing a more conservative IT cost estimate. Confidence also affects the caveats in the recommendation output.",
  },
  {
    question: "Why does the tool flag a warning when my average object size is below 128 KB?",
    answer: "Standard-IA, One Zone-IA, and all three Glacier classes have a minimum billable object size of 128 KB. An object that is actually 10 KB is billed as if it were 128 KB. For a bucket with 10 million objects averaging 10 KB, the effective billed storage in Standard-IA would be roughly 1.2 TB even though you only stored 100 GB. This inflates costs in those classes significantly and can make Standard cheaper overall despite its higher nominal rate.",
  },
  {
    question: "What does the mutable data toggle do?",
    answer: "Mutable data means objects are regularly overwritten rather than written once and kept unchanged. When an object is overwritten in a class with a minimum duration requirement, AWS charges the remaining minimum duration as a penalty on the old version, then starts a new clock on the replacement. For a bucket where objects are updated every two weeks in Standard-IA, this means paying the 30-day minimum penalty on every update cycle. Toggling mutable data on includes this penalty in the total cost calculation.",
  },
  {
    question: "How accurate is this tool compared to my actual AWS bill?",
    answer: "For a typical workload, outputs should be within 5 to 15 percent of actual AWS billing. The main sources of difference are: S3 replication costs are not modeled, EDP discounts are not modeled, and pricing is updated periodically but may lag AWS rate changes by a few weeks. Data transfer out to the internet is now modeled in the Advanced Costs section. The pricing last-verified date is shown in the tool header. For precise validation, compare this tool output against your AWS Cost and Usage Report for the same bucket and month.",
  },
  {
    question: "What does the tool not model?",
    answer: "Current known limitations include: EDP (Enterprise Discount Program) agreements, S3 replication charges for cross-region or same-region replication, lifecycle policy modeling for data transitioning through multiple classes over time, NAT Gateway fees, S3 Versioning cost impact from accumulating noncurrent versions, incomplete multipart upload storage, S3 Object Lock retention costs, and costs in AWS GovCloud and China regions. Data transfer out to the internet is now modeled in the Advanced Costs section.",
  },
  {
    question: "Why is S3 Express One Zone shown separately from the other storage classes?",
    answer: "Express One Zone uses a completely different bucket type called a directory bucket and cannot be mixed with objects from other storage classes. It has no lifecycle transition support, no versioning, and no cross-region replication. Moving to or from Express One Zone requires explicitly copying data between different bucket types, which is a significant operational change rather than a simple class transition.",
  },
  {
    question: "When should I use Glacier Flexible Retrieval instead of Glacier Instant Retrieval?",
    answer: "Use Glacier Flexible Retrieval when you can tolerate a wait of hours to access your data and you access it very rarely, perhaps once or twice a year. Standard retrieval at $0.01 per GB is cheaper than Glacier Instant at $0.03 per GB. The critical difference is that Glacier Flexible data is not available in real time. If there is any possibility your application needs data immediately, Glacier Instant is the safer choice.",
  },
  {
    question: "What is Reduced Redundancy Storage and should I still be using it?",
    answer: "Reduced Redundancy Storage is a legacy S3 storage class that AWS deprecated and no longer recommends. It stores data in fewer locations than Standard, offering lower durability at essentially the same price. There is no cost benefit and a meaningful durability downgrade. If your bucket is on RRS, this tool will recommend migrating to Standard or Standard-IA depending on your access patterns.",
  },
  {
    question: "The tool recommends a different class than my other cost tool. Why?",
    answer: "Most cost optimization tools model storage costs only. They take your current storage volume, apply the rate for a cheaper class, and report the difference as savings. This tool additionally models retrieval fees, request costs, minimum duration penalties, Intelligent-Tiering monitoring fees, and small object billing inflation. For workloads with significant retrieval volume or high object counts, these additional costs materially change the recommendation. If there is a discrepancy, check whether the other tool is accounting for retrieval costs.",
  },
  {
    question: "What does the sensitivity table tell me?",
    answer: "The sensitivity table shows what happens to the recommendation if your actual retrieval volume turns out to be half, double, or three times what you entered. This matters because retrieval volume is the input most commonly estimated rather than measured. If the recommended class changes when retrieval is doubled, measure your actual retrieval before committing to a transition. If the recommendation stays the same across all scenarios, the case for transitioning is robust.",
  },
  {
    question: "What does the break-even period mean?",
    answer: "The break-even period is the number of months until your cumulative monthly savings equal the one-time cost of transitioning objects to the new class. A break-even of 3 months means the transition pays for itself in 3 months. A break-even of 18 months means you need to commit to the new class for a year and a half before it is financially justified. Use break-even alongside your expected retention period. If you only plan to keep data for 12 more months, a break-even of 18 months means the transition is not worth making.",
  },
  {
    question: "Why does transitioning 1 million objects cost more than transitioning 1 TB?",
    answer: "S3 lifecycle transition costs are charged per object, not per gigabyte. AWS charges a flat fee per 1,000 objects transitioned, regardless of how large or small those objects are.\n\nCurrent lifecycle transition rates:\n• Standard-IA / One Zone-IA: $0.01 per 1,000 objects\n• Glacier Instant Retrieval: $0.02 per 1,000 objects\n• Glacier Flexible Retrieval: $0.03 per 1,000 objects\n• Glacier Deep Archive: $0.05 per 1,000 objects\n\nThis means a bucket with 1 billion small objects (e.g. log files) costs up to $50,000 to transition to Deep Archive — regardless of whether the total data is 10 GB or 10 TB. The calculator models this correctly using your object count input. If you have a high object count relative to your storage volume, check the Warnings section for a transition cost dominance alert.",
  },
  {
    question: "What is the minimum storage duration charge?",
    answer: "Several S3 storage classes have a minimum billing period. If you delete, overwrite, or transition an object out of the class before this period expires, AWS charges you for the remaining days anyway.\n\nMinimum durations:\n• S3 Standard-IA / One Zone-IA: 30 days\n• S3 Glacier Instant Retrieval: 90 days\n• S3 Glacier Flexible Retrieval: 90 days\n• S3 Glacier Deep Archive: 180 days\n\nExample: storing 1 TB in Glacier Instant for 30 days then deleting it still costs the full 90-day charge. The calculator models this as an \"early deletion penalty\" shown in the break-even analysis when your expected retention is shorter than the class minimum.",
  },
  {
    question: "Why might Glacier retrieval costs be overstated?",
    answer: "The calculator estimates Glacier retrieval request costs using your monthly GET request count as a proxy. In practice, Glacier workflows use restore requests (which are fewer and less frequent than standard GETs), so actual retrieval costs may be lower than shown. Treat Glacier retrieval cost estimates as a conservative upper bound.",
  },
  {
    question: "My bucket already has a lifecycle policy. What should I do?",
    answer: "Use the Mixed Storage Classes mode in this tool. Enter the current GB distribution across each class as shown in S3 Storage Lens or your cost tooling. The tool will calculate your true current total cost across all active classes and model what consolidating to a single target class would cost, including retrieval fees that most tools ignore.",
  },
  {
    question: "How do I find the inputs this tool needs if I only have access to a third-party cost tool?",
    answer: "Storage GB and current storage class are available in most third-party tools including CloudHealth and Cloudability. Object count is usually available at the bucket level. Monthly GET Requests and Monthly Retrieval GB are less commonly surfaced. For retrieval GB specifically, most third-party tools do not expose this because they read from billing data rather than CloudWatch metrics. AWS CloudWatch is the most reliable source for these two inputs.",
  },
  {
    question: "My organization has an EDP discount with AWS. Does this tool account for it?",
    answer: "Not yet — EDP modeling is on the roadmap. Enterprise Discount Program agreements are private and customer-specific, so the tool cannot know your rate automatically. In the meantime, you can apply your EDP percentage manually: multiply any cost figure shown by (1 - your EDP rate). For example, at 15% EDP, multiply by 0.85. The recommended storage class will not change — EDP applies proportionally across all S3 storage classes, so relative cost differences are unchanged. A future update will add an optional EDP input field to handle this automatically.",
  },
  {
    question: "My application uses CloudFront to serve S3 content. Should I enter data transfer costs?",
    answer: "No. S3-to-CloudFront data transfer is completely free. Only enter a value in the Data Transfer Out field if your application transfers data from S3 directly to the internet or to another cloud provider, bypassing CloudFront. S3-to-EC2 in the same region and S3-to-Lambda are also free and should not be counted.",
  },
  {
    question: "Some of my S3 workloads could use Glacier Flexible or Deep Archive. Why are they not always recommended?",
    answer: "By default the tool excludes Glacier Flexible Retrieval and Deep Archive from recommendations because these classes require a restore request before data is accessible — they are not available in real time. If your workload can genuinely tolerate waiting minutes to hours (compliance archives, cold disaster recovery, long-term log retention), turn off the Requires Immediate Access toggle in the Access Patterns section. The tool will then include these classes in the recommendation and show their full savings potential.",
  },
];

export function LearnTab() {
  return (
    <div className="mx-auto max-w-[760px] px-6 py-12">
      {/* Section 1: How S3 Pricing Works */}
      <section>
        <h2 className="text-2xl font-bold text-[#111827] mb-6">
          How S3 Pricing Works
        </h2>
        <div className="space-y-4 text-[15px] leading-[1.7] text-[#374151]">
          <p>
            When you store data in Amazon S3, AWS does not charge you one flat rate. Your bill is made up of four separate components, and understanding each one is the difference between a useful cost estimate and a misleading one.
          </p>
          <p>
            <strong>Storage cost.</strong> You pay for the total volume of data stored, measured in gigabytes per month. The rate depends entirely on which storage class your objects are in. S3 Standard costs $0.023 per GB. S3 Glacier Deep Archive costs $0.00099 per GB. That is a 23 times difference in storage price between the two extremes.
          </p>
          <p>
            <strong>Request cost.</strong> Every time your application reads or writes an object, AWS charges a small fee per request. These fees seem tiny individually but add up quickly at scale. A bucket receiving 10 million GET requests per month adds around $4 in request costs. At 500 million requests that becomes $200 per month from requests alone.
          </p>
          <p>
            <strong>Retrieval cost.</strong> Some storage classes charge a per-gigabyte fee every time data is downloaded or restored. S3 Standard and S3 Intelligent-Tiering do not charge for retrieval. Standard-IA, One Zone-IA, and all three Glacier classes do. This is the cost component that most tools miss and the one most likely to make a recommendation look better on paper than it is in practice.
          </p>
          <p>
            <strong>Minimum duration penalty.</strong> Lower-cost storage classes come with a commitment period. If you delete, overwrite, or move an object before that period ends, AWS still charges you for the full duration. Standard-IA and One Zone-IA have a 30-day minimum. Glacier Instant Retrieval and Glacier Flexible Retrieval have a 90-day minimum. Glacier Deep Archive has a 180-day minimum.
          </p>
          <blockquote className="border-l-4 border-[#e5e7eb] pl-4 italic text-[#6b7280]">
            This tool models all four cost components together. Most third-party tools model storage cost only. The difference in recommendations can be significant.
          </blockquote>

          <h3 className="text-lg font-semibold text-[#374151] pt-4">
            The Four Most Common Mistakes
          </h3>
          <p>
            <strong>1. Ignoring retrieval costs when choosing Glacier.</strong> Moving a large dataset to Glacier Instant Retrieval and saving 80% on storage looks compelling. But if your application retrieves 30% of that data each month, the retrieval fees can exceed the entire storage saving. Always enter your monthly retrieval volume into the tool before accepting any Glacier recommendation.
          </p>
          <p>
            <strong>2. Using Intelligent-Tiering for small objects.</strong> IT charges a monitoring fee per object above 128 KB. If your bucket has 100 million objects averaging 10 KB, you are paying the monitoring fee for objects that will never tier down because they are too small. The monitoring cost is real; the savings are not.
          </p>
          <p>
            <strong>3. Transitioning mutable data to IA or Glacier classes.</strong> If your application regularly overwrites objects, each overwrite triggers a new minimum duration period. A file overwritten every two weeks in Standard-IA incurs the 30-day minimum penalty on every overwrite cycle.
          </p>
          <p>
            <strong>4. Assuming Glacier is always the cheapest.</strong> Add the 40 KB per-object metadata overhead, the 180-day minimum duration, and any retrieval costs, and the effective cost for a bucket with billions of small objects can exceed Standard-IA or even Standard. True total cost requires modeling all four components, not just the storage rate.
          </p>
        </div>
      </section>

      {/* Divider */}
      <hr className="border-[#e5e7eb] my-12" />

      {/* Section 2: Storage Classes Explained */}
      <section>
        <h2 className="text-2xl font-bold text-[#111827] mb-6">
          Storage Classes Explained
        </h2>
        <div className="space-y-6 text-[15px] leading-[1.7] text-[#374151]">
          <div>
            <h3 className="text-lg font-semibold text-[#374151] mb-2">
              S3 Standard
            </h3>
            <p>
              The default and the benchmark everything else is measured against. No minimum duration, no retrieval charges, no object size penalties. Your data is available instantly. The right choice for data accessed frequently or unpredictably, and for data where you cannot tolerate any delay in access.
            </p>
          </div>
          <div>
            <h3 className="text-lg font-semibold text-[#374151] mb-2">
              S3 Intelligent-Tiering
            </h3>
            <p>
              The only storage class that automatically moves objects between tiers based on actual access patterns. Objects not accessed in 30 days move to Infrequent Access. After 90 days they move to Archive Instant Access. When an object is accessed, it moves back automatically. You pay a monitoring fee of $0.0025 per 1,000 objects per month for every object above 128 KB. For buckets with high object counts and small total storage, this fee can exceed the savings from tiering.
            </p>
          </div>
          <div>
            <h3 className="text-lg font-semibold text-[#374151] mb-2">
              S3 Standard-IA
            </h3>
            <p>
              Lower storage costs at $0.0125 per GB but charges $0.01 per GB on every retrieval. Has a 30-day minimum storage duration and a 128 KB minimum billable object size. Works well for data accessed infrequently, stored for long periods, and consisting of reasonably large objects.
            </p>
          </div>
          <div>
            <h3 className="text-lg font-semibold text-[#374151] mb-2">
              S3 One Zone-IA
            </h3>
            <p>
              Identical to Standard-IA except data is stored in only one availability zone. Approximately 20% cheaper at $0.01 per GB. If that availability zone experiences a disruption, your data could be lost. Appropriate for data that can be recreated or is replicated elsewhere. Not appropriate for primary copies of irreplaceable data.
            </p>
          </div>
          <div>
            <h3 className="text-lg font-semibold text-[#374151] mb-2">
              S3 Glacier Instant Retrieval
            </h3>
            <p>
              Same millisecond access as Standard-IA but lower storage at $0.004 per GB and higher retrieval at $0.03 per GB. Requires a 90-day minimum. Designed for data accessed roughly once per quarter or less. The storage savings are substantial but any increase in access frequency erodes those savings quickly through retrieval costs.
            </p>
          </div>
          <div>
            <h3 className="text-lg font-semibold text-[#374151] mb-2">
              S3 Glacier Flexible Retrieval
            </h3>
            <p>
              A true archival class. Data is not available immediately. You must submit a restore request and wait 1 to 5 minutes for expedited, 3 to 5 hours for standard, or 5 to 12 hours for bulk. Bulk retrieval is free. Storage costs $0.0036 per GB with a 90-day minimum. Use for data you need to retain for years but access no more than once or twice per year.
            </p>
          </div>
          <div>
            <h3 className="text-lg font-semibold text-[#374151] mb-2">
              S3 Glacier Deep Archive
            </h3>
            <p>
              The lowest-cost storage in AWS at $0.00099 per GB per month, roughly 23 times cheaper than Standard. Retrieval takes 12 to 48 hours. Has a 180-day minimum duration and a 40 KB metadata overhead per object. Appropriate for data retained for compliance or legal reasons that will almost never be accessed in normal operations.
            </p>
          </div>
          <div>
            <h3 className="text-lg font-semibold text-[#374151] mb-2">
              S3 Express One Zone
            </h3>
            <p>
              A high-performance class using a different bucket type entirely. Delivers single-digit millisecond latency and can handle up to 2 million requests per second. Storage costs $0.11 per GB, nearly 5 times more than Standard. This is not a cost optimisation class. It is a performance tier for latency-sensitive, high-throughput workloads. This tool evaluates it separately from the main cost comparison.
            </p>
          </div>
          <div>
            <h3 className="text-lg font-semibold text-[#374151] mb-2">
              Reduced Redundancy Storage
            </h3>
            <p>
              A deprecated class that AWS no longer recommends. It offers lower durability than Standard at essentially the same price. There is no cost benefit and a meaningful durability downgrade. If your bucket is on RRS, this tool will always recommend migrating away from it.
            </p>
          </div>
        </div>
      </section>

      {/* Divider */}
      <hr className="border-[#e5e7eb] my-12" />

      {/* Section 3: FAQ */}
      <section>
        <h2 className="text-2xl font-bold text-[#111827] mb-6">
          Frequently Asked Questions
        </h2>
        <FaqAccordion items={FAQ_ITEMS} />
      </section>
    </div>
  );
}
